### ISSUE TITLE
Project logging

### ISSUE THREAD

**Issue by eugenepeh** [CS2103AUG2017-T12-B3/main#14]
Hello Shi Jing, 

I've consulted Prof. Damith, your project logging has to be done in the repo's "Projects".

**Comment by wshijing** [comment]
So I have to include my user stories, use cases and NFRs in the project board?

**Comment by eugenepeh** [comment]
@wshijing hmm the instructions in https://nus-cs2103.github.io/website/admin/index.html actually says you can... let me clarify further for you.

**Comment by eugenepeh** [comment]
@wshijing 
Here's the updated reply from Prof, hope it clears it up
>The github project board is recommended because eventually they'll be tracking project progress as github issues anyway, might as well put the user stories in github from the beginning. But they can use any other tool to record user stories if they want, provided they use github issue tracker to track project progress later.

If you have any administrative questions, you can post it in slack/forum, Prof. Damith will answer your questions over there.

**Comment by wshijing** [comment]
Alrights! I will just input it in the project board! Thank you for clarifying!
