### ISSUE TITLE
As a user I want to load contacts from a pre-existing address book

### ISSUE THREAD

**Issue by jonatanlehtinen** [CS2103AUG2017-T12-B3/main#23]
Implementing a load command, which loads the contact from a specified pre-existing address book to the address book which is currently used.

- [x] Add support for load command
- [x] Add support for creating a new address book and merge address books
- [x] Write tests for this new feature

**Comment by joppeel** [comment]
- [x] Add support for load command
- [ ] Add support for creating a new address book and merge address books
- [ ] Write tests for this new feature
