### ISSUE TITLE
As a user I want to see phone numbers in proper format

### ISSUE THREAD

**Issue by aggarwalRuchir** [CS2103AUG2017-T12-B3/main#34]
Currently, the phone numbers displayed in contact cards are just plain numbers. Displaying phone numbers in proper format(national convention) would make it easier for the user to see the phone numbers. For example, a Singapore number 81049754 would be displayed as 8104-9754.

- [x] Update code
- [x] Update tests
- [x] Update documentation

**Comment by eugenepeh** [comment]
@aggarwalRuchir @joppeel @wshijing 

`move all incomplete issues to a future milestone and close the milestone`

[Warning] you guys haven't close the v1.3 milestone.

**Comment by eugenepeh** [comment]
@aggarwalRuchir @wshijing @joppeel , to close the milestone after closing all the issues / pull requests, you need to go to `Issues > Milestones > Close the milestone` as well
