### ISSUE TITLE
adding person with no profile picture

### ISSUE THREAD

**Issue by jelneo** [CS2103AUG2017-T12-B3/main#47]
![image](https://user-images.githubusercontent.com/28497440/32362808-fe8c4836-c0a6-11e7-86b1-7265df1e927a.png)

1. Perhaps it would be better to make adding a profile picture optional because sometimes the user might not have a picture to upload. Maybe you can use a default photo instead if no picture is specified.
2. Just curious, where will the profile picture be shown?

**Comment by kenpaxtonlim** [comment]
This bug is not present in my testing. When I enter a command incorrectly, an error message is shown as expected. You might want to try again.

**Comment by jelneo** [comment]
yup have restarted the app and it works now
